### PR TITLE
Fixed buffer allocation error

### PR DESCRIPTION
**Pull request by LMSC-NTappy**
Hello, 

I have found this modification of buffer allocation to fix the issue I opened in #12. 

If you want to verify that it does not create any unexpected behaviour, I would suggest you merge it in the main.

Best Regards

Nicolas

### CODE REVIEW

**Comment by AlexShkarin** [comment]
Dear Nicolas,

Thank you for the investigation!

I didin't realize before that those two strides are different (they were always the same on my test cameras), but you are right, the readout stride is the correct one. However, according to the documentation, there are more caveats to that, with one readout having potentially several frames (and one frame having several ROIs...). I think, I would need to address this as well before merging the changes to main and releasing the new package version. In light of that, I'm not sure it makes sense to merge your push request, since there will be more extensive rewrites before the new package version is published. I hope, this is OK with you.

Sincerely,

Alexey.

**Comment by LMSC-NTappy** [comment]
Dear Alexey,

I think that merging now only contributes to increasing the stability of the release at no downside, but the choice is yours. Both are fine and ultimately the choice is yours. I have a version that works for my applications now, so no need to press a release :)

Let me know if I can be of any help.

**Comment by AlexShkarin** [comment]
Dear Nicholas,

I've implemented your fix together with the necessary changes for the multi-frame readouts in the lates ``dev`` branch commit ([d619254](https://github.com/AlexShkarin/pyLabLib/commit/d61925461a626ce619b56a20e25e51f2736e316d)). I would appreciate it if you could check it at some point, especially the multi-frame functionality (it can be enabled by changing ``"Readout Control Mode"`` attribute and checked via ``Frames per Readout`` attribute, which would be more than 1).

Sincerely,

Alexey.

**Comment by LMSC-NTappy** [comment]
Dear Alexey,

Wow that was fast! The changes in the commit look good to me.

I will test it with a snippet of code and report the results to you

**Comment by LMSC-NTappy** [comment]
Dear Alexey,

sorry it will take some more time, I will try to test this within the week

**Comment by LMSC-NTappy** [comment]
So After more testing: turns out the only way to have >1 frames per readout is to use the row-windowed kinetics mode of the Camera. It does raise an error upon committing the parameters to the CCD though.

Here is the code

```python
import pylablib.devices.PrincetonInstruments as PI
cam = PI.PicamCamera('6666666')

cam.cav['Frames per Readout']
#1
cam.set_attribute_value('Readout Control Mode','Kinetics')
cam.set_attribute_value('Kinetics Window Height',10)

cam.cav['Frames per Readout']
#10 
cam.setup_acquisition()
cam.start_acquisition()
---------------------------------------------------------------------------
PicamLibError                             Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_11636/3812717633.py in <module>
----> 1 cam.start_acquisition()

c:\users\admin\documents\pymodaq_dev\pylablib\pylablib\devices\PrincetonInstruments\picam.py in start_acquisition(self, *args, **kwargs)
    518         self._waited_readouts=0
    519         self._frame_counter.reset(self._buffer_readouts*self._frames_per_readout)
--> 520         self._commit_parameters()
    521         lib.Picam_StartAcquisition(self.handle)
    522     def stop_acquisition(self):

c:\users\admin\documents\pymodaq_dev\pylablib\pylablib\devices\PrincetonInstruments\picam.py in _commit_parameters(self)
    475 
    476     def _commit_parameters(self):
--> 477         failed=lib.Picam_CommitParameters(self.handle)
    478         if failed:
    479             failed=[_get_str(PicamEnumeratedType.PicamEnumeratedType_Parameter,p) for p in failed]

c:\users\admin\documents\pymodaq_dev\pylablib\pylablib\devices\PrincetonInstruments\picam_lib.py in Picam_CommitParameters(self, camera)
    306         return self.destroy_convert(*self.Picam_GetParameters_lib(camera),conv=lambda v:v,destroy=self.Picam_DestroyParameters)
    307     def Picam_CommitParameters(self, camera):
--> 308         return self.destroy_convert(*self.Picam_CommitParameters_lib(camera),conv=lambda v:v,destroy=self.Picam_DestroyParameters)
    309 
    310     def _parse_rois(self, rois):

<string> in <lambda>(camera_or_accessory)

c:\users\admin\documents\pymodaq_dev\pylablib\pylablib\core\utils\ctypes_wrap.py in wrapped_func(*vargs, **kwargs)
    276                     return a
    277             call_args=[_to_call_arg(n,t,a) for (n,t,a) in zip(argnames,prep_argtypes,func_args)]
--> 278             retval=func(*call_args)
    279             res=self._convert_results(rvals or [None],dict(zip(argnames,func_args)),retval,kwargs,rconv)
    280             if (not self.tuple_single_retval) and len(res)==0:

c:\users\admin\documents\pymodaq_dev\pylablib\pylablib\devices\PrincetonInstruments\picam_lib.py in errchecker(result, func, arguments)
     42     def errchecker(result, func, arguments):  # pylint: disable=unused-argument
     43         if result not in passing:
---> 44             raise PicamLibError(func.__name__,result,lib=lib)
     45         return result
     46     return errchecker

PicamLibError: function 'Picam_CommitParameters' raised error 28(PicamError_InvalidParameterValues): Invalid Parameter Values
```

Note that the setup_acquisition runs without raising an error. Also, upon setting a 100-rows window height, the Frames per Readout argument still gives me a value of 2 which might be fine but seems counter-intuitive to me. Any idea why that is?

```python
cam.set_attribute_value('Readout Control Mode','Kinetics')
cam.set_attribute_value('Kinetics Window Height',100)

cam.cav['Frames per Readout']
#2 
```

Cheers

Nicolas

**Comment by LMSC-NTappy** [comment]
I just realised that the max height for kinetics is 50 rows, which explaines the 2 frames per readout... my mistake!


Oh and sorry for missing the most important point: the binning works beautifully now, this is brilliant!

I guess you want to keep this PR open until the multi frame readout is fixed ?

**Comment by AlexShkarin** [comment]
Sorry, it took me a while to check the issue.

It seems like setting the mode to ``Kinetics`` invalidates the current ROI, since its height is still more than 10px. That's why it can not start the acquisition. The ROI needs to be set back to a valid one by calling ``.set_roi()`` (calling it without any parameters simply sets it to the maximal possible one with no binning). It worked with my camera, but it would be good if you could check it as well at some point (no rush!)

I'm not sure I would want to address it in code at this point, since with the direct setting of parameters it's hard to control for all possible combination and catch all of the issues. At some point I will, likely, add something like ``set_readout_mode`` method, and there it will check for some conflicts like this one. For now I just added a note to the documentation (to be updated with the new release).

**Comment by LMSC-NTappy** [comment]
> Sorry, it took me a while to check the issue.

Please don't apologize, you are being so generous and efficient in this work =)

In any case, it works fine this is brilliant. Here is the code that I used to test it and it returns exactly the expected number of frames.

```python
# ReadCtrlMode = ['Full Frame','Kinetics']
ReadCtrlMode = ['Kinetics']

KinWindowHeight = [2,5,10,20]
frames = []
for RCM,KWH in itertools.product(ReadCtrlMode,KinWindowHeight):
    print(RCM,KWH)
    cam.set_attribute_value('Readout Control Mode',RCM)
    cam.set_attribute_value('Kinetics Window Height',KWH)
    cam.set_roi()
    cam.setup_acquisition()
    cam.start_acquisition()
    cam.wait_for_frame()
#     img = cam.read_oldest_image()
    img = cam.read_multiple_images()
    cam.stop_acquisition()
    frames.append(img)
#     frames.append(cam.grab())
```

>I'm not sure I would want to address it in code at this point, since with the direct setting of parameters it's hard to control for all possible combination and catch all of the issues. At some point I will, likely, add something like set_readout_mode method, and there it will check for some conflicts like this one. For now I just added a note to the documentation (to be updated with the new release).

It is entirely up to you.

I think it is safe to close this issue, now.

**Pull request closed without merging**
